config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: 'pages#dashboard', as: :authenticated_root
  end
  root to: 'pages#home'

  get '/pages/about', to: 'pages#about', as: 'about'

  resources :pets, only: [:new, :create, :show] do
    member do
      post :add_picture
      delete :remove_picture
    end
  end

  #FRIENDS ROUTES
  post '/pets/:id', to: 'friends#search_friend', as: 'search_friend'
  post "/friends/add" => "friends/add"
  post "/friends/reject" => "friends/reject"
  post "/friends/remove" => "friends/remove"
  resources :friends, only: [:new, :index, :create]

  #CALENDAR ROUTES
  resources :events

  #EXPENSES ROUTES
  # resources :expenses do
  #  resources :expense_types
  # end

  # resources :budgets do
  #   resources :expense_types
  # end

  resources :expense_types do
    resources :expenses, except: [:show]
    resources :budgets
  end

  # EXPLORE ROUTES

  # resources :places, only: [:new] do
  #   resources :favourite_places, except: [:edit, :update]
  # end

  resources :places, only: [:index, :show]
  get '/places/check_place/:id', to: 'places#check_place', as: 'check_place'
  post '/places/add_place', to: 'places#add_place', as: 'add_place'

  resources :favourite_places, only: [:index, :destroy]
  get '/favourite_places/:id', to: 'favourite_places#add', as: 'add_to_favourites'

  #PHOTOS ROUTES
  resources :photos, only: [:show, :index, :new]

  #CHATROOM ROUTES
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :pet
  belongs_to :expense_type
  validates :month, presence: true
  validates :amount, presence: true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :messages
    has_one_attached :photo
end

app/models/dashboard_category.rb
class DashboardCategory < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :pet
end

app/models/expense.rb
class Expense < ApplicationRecord
    belongs_to :pet
    belongs_to :expense_type
    validates :description, presence: true
end

app/models/expense_type.rb
class ExpenseType < ApplicationRecord
    has_many :budgets, dependent: :destroy
    has_many :expenses, dependent: :destroy
end

app/models/favourite_place.rb
class FavouritePlace < ApplicationRecord
  belongs_to :place
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_many :events, dependent: :destroy
  has_many :budgets, dependent: :destroy
  has_many :expenses, dependent: :destroy
end

app/models/place.rb
class Place < ApplicationRecord
    geocoded_by :address
    after_validation :geocode, if: :will_save_change_to_address?
    has_one :favourite_place
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, presence: true
  has_one :pet, dependent: :destroy
  has_one :favourite_place, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_friendship

  def friends?
    self.friends
end

def friend_requests?
    self.requested_friends.any?
end

def requested_friends?
    self.pending_friends.any?
end

def invite_friend(user)
    self.friend_request(user)
end

def not_friends
    potential = []
    User.all.each do |user|
        if (self.friends_with?(user) != true && self != user && self.friends.include?(user) != true && self.pending_friends.include?(user) != true && self.requested_friends.include?(user) != true)
            potential << user
        end
    end
    potential
end



end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
    def show
        @pet = Pet.find(params[:id])
    end
    def new
        @pet = Pet.new
    end
    def create
        @pet = Pet.new(pet_params)
        current_user.pet = @pet
        if @pet.save
            redirect_to pet_path(@pet)
        else
            render new
        end
    end
    def add_picture
        @pet = Pet.find(params[:id])
        @pet.photos.attach(io: params[:pet][:photo], filename: "#{@pet.id}_picture", content_type: 'image/png')
        redirect_to @pet
    end
    def remove_picture
        @photo = ActiveStorage::Attachment.find(params[:id])
        @photo.purge
        redirect_to pet_path(@photo.record_id)
    end
    
    private
    def pet_params
        params.require(:pet).permit(:breed, :name, :birthday, :microchip)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/pets/new.html.erb
<div class="row my-5">
    <div class="col-9 mx-auto">
        <div class="container">
            <div class="row">
                <div class="col-2 mx-auto mb-2">
                    <%= image_tag('paw-logo.svg', class: 'logo') %>
                </div>
            </div>
            <div class="row border mt-2">
                <div class="col-12 mx-auto text-center">
                    <h4>We would love to know more about your bestie!!</h4>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row mx-3">
    <div class="col-12 mx-auto">
        <%= simple_form_for @pet do |f| %>
        <%= f.error_notification %>

        <div class="form-group form-icons">
            <span class="fas fa-file-signature"></span>
            <%= f.input :pet_name,
                label: false,
                placeholder: 'Pet name',
                required: true,
                autofocus: true
            %>
        </div>

        <div class="form-group form-icons ">
            <span class="fas fa-dog"></span>
            <%= f.input :breed,
                label: false,
                placeholder: 'Breed',
                required: true,
                autofocus: true
                %>
        </div>

        <div class="form-group form-icons ">
            <span class="fas fa-birthday-cake"></span>
            <%= f.input :birthday, as: :string, label: false, placeholder: 'Birthday',required: true, input_html: {class: "datepicker"} %>
        </div>

        <div class="form-group form-icons ">
            <span class="fas fa-microchip"></span>
            <%= f.input :microchip, as: :string, label: false, placeholder: 'Chip ID',required: true %>
        </div>

        <div class="form-actions ml-4 mb-3">
            <%= f.button :submit, "Add pet", class: "button button-lg primary-blue my-3" %>
        </div>
        <% end %>
    </div>
</div>

app/views/pets/show.html.erb
<div class="categories-header photos-header mx-auto">
    <%= render 'components/header', path: root_path %>
    <h3 class="categories-text text-center">Photos</h3>
    <div class=" profile-header">
        <div class="profile-pic">
            <% if @pet.photos.any? %>
            <%= image_tag(@pet.photos.first, class: 'avatar rounded-circle') %>
            <%end%>
        </div>
        <div class="profile-text">
            <h3><%= @pet.pet_name %></h3>
        </div>
    </div>
</div>
<div class="pets-main">
    <div class="pets-body">
        <% @pet.photos.each do |photo| %>
        <div class="card">
            <%= link_to photo_path(photo.id) do %>
            <%= cl_image_tag photo.key, :aspect_ratio=>"1:1", :radius=>"20:80", crop: :fill %>
            <% end %>
        </div>
        <% end %>
        <% if current_user == @pet.user %>
        <%= render 'components/fab', path: new_photo_path, modal: true, obj: @pet, url: add_picture_pet_path(@pet) %>
        <%end%>
    </div>
</div>