config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: 'pages#dashboard', as: :authenticated_root
  end
  root to: 'pages#home'

  get '/pages/about', to: 'pages#about', as: 'about'

  resources :pets, only: [:new, :create, :show] do
    member do
      post :add_picture
      delete :remove_picture
    end
  end

  #FRIENDS ROUTES
  post '/pets/:id', to: 'friends#search_friend', as: 'search_friend'
  post "/friends/add" => "friends/add"
  post "/friends/reject" => "friends/reject"
  post "/friends/remove" => "friends/remove"
  resources :friends, only: [:new, :index, :create]

  #CALENDAR ROUTES
  resources :events

  #EXPENSES ROUTES
  # resources :expenses do
  #  resources :expense_types
  # end

  # resources :budgets do
  #   resources :expense_types
  # end

  resources :expense_types do
    resources :expenses, except: [:show]
    resources :budgets
  end

  # EXPLORE ROUTES

  # resources :places, only: [:new] do
  #   resources :favourite_places, except: [:edit, :update]
  # end

  resources :places, only: [:index, :show]
  get '/places/check_place/:id', to: 'places#check_place', as: 'check_place'
  post '/places/add_place', to: 'places#add_place', as: 'add_place'

  resources :favourite_places, only: [:index, :destroy]
  get '/favourite_places/:id', to: 'favourite_places#add', as: 'add_to_favourites'

  #PHOTOS ROUTES
  resources :photos, only: [:show, :index, :new]

  #CHATROOM ROUTES
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :pet
  belongs_to :expense_type
  validates :month, presence: true
  validates :amount, presence: true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :messages
    has_one_attached :photo
end

app/models/dashboard_category.rb
class DashboardCategory < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :pet
end

app/models/expense.rb
class Expense < ApplicationRecord
    belongs_to :pet
    belongs_to :expense_type
    validates :description, presence: true
end

app/models/expense_type.rb
class ExpenseType < ApplicationRecord
    has_many :budgets, dependent: :destroy
    has_many :expenses, dependent: :destroy
end

app/models/favourite_place.rb
class FavouritePlace < ApplicationRecord
  belongs_to :place
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_many :events, dependent: :destroy
  has_many :budgets, dependent: :destroy
  has_many :expenses, dependent: :destroy
end

app/models/place.rb
class Place < ApplicationRecord
    geocoded_by :address
    after_validation :geocode, if: :will_save_change_to_address?
    has_one :favourite_place
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, presence: true
  has_one :pet, dependent: :destroy
  has_one :favourite_place, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_friendship

  def friends?
    self.friends
end

def friend_requests?
    self.requested_friends.any?
end

def requested_friends?
    self.pending_friends.any?
end

def invite_friend(user)
    self.friend_request(user)
end

def not_friends
    potential = []
    User.all.each do |user|
        if (self.friends_with?(user) != true && self != user && self.friends.include?(user) != true && self.pending_friends.include?(user) != true && self.requested_friends.include?(user) != true)
            potential << user
        end
    end
    potential
end



end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
    before_action :find_expense_type
    before_action :find_budget, only: [:show, :edit, :update, :destroy]

    def index
        @budgets = @expense_type.budgets
    end

    # def show

    # end

    def new
        @budget = Budget.new
    end

    def create
        @budget = Budget.new(budget_params)
        @budget.pet = current_user.pet
        @budget.expense_type = @expense_type
        if @budget.save
            flash[:notice] = "Budget added successfully"
            redirect_to expense_type_budgets_path
        else
            flash[:alert] = "Budget could not be added. Please try again"
            render :new
        end
    end

    def edit

    end

    def update       
        @budget.expense_type = @expense_type
        @budget.pet = current_user.pet
        if @budget.update(budget_params)
            flash[:notice] = "Budget updated successfully"
            redirect_to expense_type_budgets_path
        else
            flash[:alert] = "Budget could not be updated. Please try again"
            render :edit
        end
    end

    def destroy
        @budget.destroy
        flash[:notice] = "Budget successfully deleted"
        redirect_to expense_type_budgets_path
    end 

    private

    def find_expense_type
        @expense_type = ExpenseType.find(params[:expense_type_id])
    end

    def find_budget
        @budget = @expense_type.budgets.find(params[:id])
    end

    def budget_params
        params.require(:budget).permit(:amount, :month)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/budgets/_form.html.erb
<div class="categories-header">
    <%= render 'components/header', path: expense_type_budgets_path %>
</div>
<div class="row mx-auto flex-column">
    <div class="col my-3">
        <h5><%= budget.id ? "Update #{@expense_type.name} budget" : "Add a new #{@expense_type.name} budget"%></h5>
    </div>
    <div class="col">
        <%= simple_form_for([@expense_type, budget]) do |f| %>
        <%= f.input :amount, as: :integer, required: true%>
        <%= f.input :month, collection: (1..12).map{|i| [I18n.t("date.month_names")[i], i]}, required: true %>

        <%= f.button :submit, "#{budget.id ? "Update" : "Add" }", class: "button button-md primary-green" %>
        <% end %>
    </div>
</div>

app/views/budgets/edit.html.erb
<%= render 'form', budget: @budget, url: expense_type_budgets_path %>

app/views/budgets/index.html.erb
<div class="categories-header">
    <%= render 'components/header', path: expense_types_path %>
    <div class="row">
        <h3 class="categories-text  mx-auto">Monthly Budgets</h3>
    </div>
</div>
<div class="row mx-2">
    <% if @budgets.length.zero? %>
    <div class="no-expense-container mx-auto mt-5">
        <p>You do not have budgets set for any month</p>
    </div>
    <%else%>
    <div class="col mx-auto mt-3">
        <div class="container">
            <%@budgets.each do |budget|%>
            <div class="row card shadow rounded flex-row p-3 my-2">
                <div class="col-3 mt-2">
                    <% if Date::MONTHNAMES[budget.month.to_i].nil? %>
                    <%= render 'components/month-card', month: budget.month[0..2] %>
                    <% else %>
                    <%= render 'components/month-card', month: Date::MONTHNAMES[budget.month.to_i][0..2] %>
                    <% end %>
                </div>
                <div class="col-9">
                    <div class="row pt-1">
                        <div class="col">
                            <h6>Budget - $<%= budget.amount%></h6>
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col">
                            <%= link_to "Edit",edit_expense_type_budget_path(@expense_type, budget), class: "button button-sm primary-green" %>
                        </div>
                        <div class="col">
                            <%= link_to "Delete",expense_type_budget_path(@expense_type, budget), method: :delete, class: "button button-sm secondary-pink" %>
                        </div>
                    </div>
                </div>
            </div>
            <%end%>
        </div>
    </div>
    <%end%>
</div>
<%= render 'components/fab', path: new_expense_type_budget_path %>

app/views/budgets/new.html.erb
<%= render 'form', budget: @budget, url: expense_type_budgets_path %>