config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: 'pages#dashboard', as: :authenticated_root
  end
  root to: 'pages#home'

  get '/pages/about', to: 'pages#about', as: 'about'

  resources :pets, only: [:new, :create, :show] do
    member do
      post :add_picture
      delete :remove_picture
    end
  end

  #FRIENDS ROUTES
  post '/pets/:id', to: 'friends#search_friend', as: 'search_friend'
  post "/friends/add" => "friends/add"
  post "/friends/reject" => "friends/reject"
  post "/friends/remove" => "friends/remove"
  resources :friends, only: [:new, :index, :create]

  #CALENDAR ROUTES
  resources :events

  #EXPENSES ROUTES
  # resources :expenses do
  #  resources :expense_types
  # end

  # resources :budgets do
  #   resources :expense_types
  # end

  resources :expense_types do
    resources :expenses, except: [:show]
    resources :budgets
  end

  # EXPLORE ROUTES

  # resources :places, only: [:new] do
  #   resources :favourite_places, except: [:edit, :update]
  # end

  resources :places, only: [:index, :show]
  get '/places/check_place/:id', to: 'places#check_place', as: 'check_place'
  post '/places/add_place', to: 'places#add_place', as: 'add_place'

  resources :favourite_places, only: [:index, :destroy]
  get '/favourite_places/:id', to: 'favourite_places#add', as: 'add_to_favourites'

  #PHOTOS ROUTES
  resources :photos, only: [:show, :index, :new]

  #CHATROOM ROUTES
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :pet
  belongs_to :expense_type
  validates :month, presence: true
  validates :amount, presence: true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :messages
    has_one_attached :photo
end

app/models/dashboard_category.rb
class DashboardCategory < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :pet
end

app/models/expense.rb
class Expense < ApplicationRecord
    belongs_to :pet
    belongs_to :expense_type
    validates :description, presence: true
end

app/models/expense_type.rb
class ExpenseType < ApplicationRecord
    has_many :budgets, dependent: :destroy
    has_many :expenses, dependent: :destroy
end

app/models/favourite_place.rb
class FavouritePlace < ApplicationRecord
  belongs_to :place
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_many :events, dependent: :destroy
  has_many :budgets, dependent: :destroy
  has_many :expenses, dependent: :destroy
end

app/models/place.rb
class Place < ApplicationRecord
    geocoded_by :address
    after_validation :geocode, if: :will_save_change_to_address?
    has_one :favourite_place
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, presence: true
  has_one :pet, dependent: :destroy
  has_one :favourite_place, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_friendship

  def friends?
    self.friends
end

def friend_requests?
    self.requested_friends.any?
end

def requested_friends?
    self.pending_friends.any?
end

def invite_friend(user)
    self.friend_request(user)
end

def not_friends
    potential = []
    User.all.each do |user|
        if (self.friends_with?(user) != true && self != user && self.friends.include?(user) != true && self.pending_friends.include?(user) != true && self.requested_friends.include?(user) != true)
            potential << user
        end
    end
    potential
end



end

app/controllers/places_controller.rb
require 'open-uri'
require 'json'
require 'rest-client'

class PlacesController < ApplicationController
    skip_before_action :verify_authenticity_token
    def index
        @place = Place.new
    end

    def show
        @is_favourite = false
        @location = Place.find_by(google_place_id: params[:id])
        if FavouritePlace.find_by(place_id: @location.id)
            @is_favourite = true
        end
    end

    def check_place
        @location = Place.find_by(google_place_id: params[:id])
        render json:@location
    end

    def add_place
        @place = Place.new(place_details_params)
        if @place.save
            render json:@place
        end 
    end

    private
    def coordinates_params
        params.require(:place).permit(:lat, :lng)
    end

    def place_details_params
        params.require(:place).permit(:address, :name, :photo, :website, :rating, :photo, :google_place_id)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<div class="row">
    <div class="col mx-auto">
        <%= form_with(model: place, local: true, data: {
        controller: :maps
    }) do |form| %>
        <div class="field search">
            <%= form.label "Search for an area" %>
            <%= form.search_field :search, name: nil, data: {target: "maps.field", action: "keydown->maps#preventSubmit" }, class: "form-control" %>
        </div>
        <div data-maps-target="map" class="map"></div>
        <%end %>
    </div>
</div>

app/views/places/index.html.erb
<div class="categories-header">
    <%= render 'components/header', path: root_path %>
    <div class="row">
        <h3 class="categories-text  mx-auto"> Explore </h3>
    </div>
</div>
<div class=" places-main">
    <%= render 'form', place: @place %>
</div>

app/views/places/show.html.erb
<div class="categories-header blue">
    <%= render 'components/header', path: places_path %>
    <div class="row">
        <div class="col-2 mx-auto">
            <%= image_tag('coffee-cup.svg', class: 'logo cafe-logo') %>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col mx-auto text-center">
            <h5><%= @location.name %></h5>
        </div>
    </div>
</div>
<div class="row my-3">
    <div class="col-9 mx-auto text-center">
        <% if @location.address.nil? %>
        <span class="text-muted ml-2">Not available</span>
        <%else%>
        <span class="text-muted ml-2"><%= @location.address %></span>
        <%end%>
    </div>
</div>
<div class="row my-3 mx-2">
    <div class="col-6">
        <i class="fas fa-phone"></i>
        <% if @location.phone.nil? %>
        <span class="text-muted ml-2">Not available</span>
        <%else%>
        <span class="text-muted ml-2"><%= @location.phone if !@location.phone.nil? %></span>
        <%end%>
    </div>
    <div class="col-4 ml-auto">
        <%@location.rating.times do%>
        <i class="fas fa-star"></i>
        <%end%>
    </div>
</div>
<div class="row">
    <% if @location.photo.nil? %>
    <span class="text-muted text-center">No photo available</span>
    <% else %>
    <%= image_tag(@location.photo, class: "cafe-image") %>
    <% end %>
</div>
<div class="row my-3 mx-2">
    <div class="col ml-auto">
        <%= link_to add_to_favourites_path(@location) do %>
        <% if @is_favourite %>
        <i class="fas fa-heart"></i>
        <%else%>
        <i class="far fa-heart"></i>
        <% end %>
        <%end%>
    </div>
</div>
<div class="row my-5 mx-2">
    <div class="col-6">
        <%= link_to 'Your favourites', favourite_places_path, class: "button button-sm primary-green" %>
    </div>
    <div class="col-6">
        <%= link_to 'Find a cafe', places_path, class: "button button-sm secondary-pink" %>
    </div>
</div>